name: Deploy to Render.com ONLY - Block Railway

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  block-railway:
    runs-on: ubuntu-latest
    steps:
    - name: Block Railway Deployments
      run: |
        echo "🚨 RAILWAY DEPLOYMENTS BLOCKED 🚨"
        echo "This repository ONLY deploys to Render.com"
        echo "Railway connection should be removed from GitHub repository settings"
        echo "All deployments must go through Render.com webhook"
        
    - name: Trigger Render Deployment
      run: |
        echo "✅ Triggering Render.com deployment"
        echo "Repository: nljolie/credli-ai"
        echo "Target: https://credli-ai.onrender.com"
        echo "Webhook should trigger automatic deployment to Render"

  verify-render-only:
    runs-on: ubuntu-latest  
    needs: block-railway
    steps:
    - name: Verify Render Configuration
      run: |
        echo "🔍 DEPLOYMENT VERIFICATION:"
        echo "✅ Railway blocked"
        echo "✅ Render.com should receive webhook"
        echo "✅ Auto-deployment to https://credli-ai.onrender.com"
        echo "❌ NO Railway deployments allowed"